modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/rempler/ResourcesForDays/issues/"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/resourcesfordays"
authors="rempler"
description='''${mod_description}'''
[[dependencies.rfd]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.rfd]]
    modId="exnihilosequentia"
    type="optional"
    versionRange="${exnihilo_range}"
    ordering="AFTER"
    side="BOTH"